// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiAIhh_wupMTadyGH-hJcASm0uIRJxzs0',
    appId: '1:1018470167099:web:aafe9cb0cba1331ec6e21e',
    messagingSenderId: '1018470167099',
    projectId: 'canarycoach-80e16',
    authDomain: 'canarycoach-80e16.firebaseapp.com',
     storageBucket: 'canarycoach-80e16.appspot.com',
    measurementId: 'G-Y713D5D992',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhtUByDSmdJ9Xde-_et-_uitSQmsWDWbU',
    appId: '1:1018470167099:android:4775ace25ceb69ccc6e21e',
    messagingSenderId: '1018470167099',
    projectId: 'canarycoach-80e16',
    storageBucket: 'canarycoach-80e16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8pV8YKFqitQaBcjV2L0t12Pmv-_0cSBk',
    appId: '1:1018470167099:ios:279ee08eb2303e60c6e21e',
    messagingSenderId: '1018470167099',
    projectId: 'canarycoach-80e16',
    storageBucket: 'canarycoach-80e16.appspot.com',
    iosBundleId: 'com.example.gymcoach',
  );
}
